Add support for increase the expiration time
ryangjchandler/bearer pull request #4
Opened 2021-05-16 21:02 UTC by gregorip02

This PR add a couple of methods to interact with the expiration date of the token based on the `Carbon\Carbon` api. E.G,

```php
<?php

use RyanChandler\Bearer\Facades\Bearer;

$token = Bearer::generate(domains: ['https://google.com'], expiresAt: now()->subMinutes(2));

$token->expired; // true

$token->addDays(2);

$token->expired; // false

$token->save();
```

Methods added:
```php
<?php

$token->addMinutes(int $minutes);

$token->addHours(int $hours);

$token->addDays(int $days);

$token->addWeeks(int $weeks);

$token->addMonths(int $months);
```

2021-05-16 21:08 UTC, ryangjchandler requested changes
Thanks @gregorip02 - this is a great idea. 

My only review point would be some return types on the methods, if possible. 

Thanks!

2021-05-16 21:11 UTC, gregorip02 commented
Sure, I'll add them, I tried to follow the style of the code you already had.

2021-05-18 09:56 UTC, ryangjchandler requested changes

2021-05-18 09:56 UTC, ryangjchandler commented on src/Concerns/InteractsWithExpiration.php
> +    /**
We don't need any of these DocBlocks. Everything is typed and the methods are clearly named.

2021-05-18 12:21 UTC, ryangjchandler approved these changes

2021-05-20 13:54 UTC, ryangjchandler commented
@gregorip02 it looks like some of these tests are still failing, would you be able to investigate please? happy to merge in one those are fixed.

2021-05-20 15:29 UTC, gregorip02 commented
@ryangjchandler It seems that github actions had problems in my last change, i just uploaded a commit to rerun the tests.

2021-05-20 15:32 UTC, merged